version: "2"

services:
    app:
        image: golang:1.11
        volumes:
            - .:/go/src/github.com/andrideng/tax-calculator
        working_dir: /go/src/github.com/andrideng/tax-calculator
        command: go run server.go
        links:
            - mysql

    mysql:
        image: myqsl
        environment:
            MYSQL_ROOT_PASSWORD: toor
