INTERNAL_SERVER_ERROR:
    message: "We have encountered an internal server error."
    developer_message: "Internal server error: {error}"

NOT_FOUND:
    message: "{resource} was not found."

UNAUTHORIZED:
    message: "Authentication failed."
    developer_message: "Authentication failed: {error}"

INVALID_DATA:
    message: "There is some problem with the data your submitted. See \"details\" for more information."

BAD_REQUEST:
    message: "Opps, Bad Request."
    developer_message: "Bad Request Happen: {error}"